/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nwn_ts_simulation_TrainBridge */

#ifndef _Included_org_nwn_ts_simulation_TrainBridge
#define _Included_org_nwn_ts_simulation_TrainBridge
#ifdef __cplusplus
extern "C" {
#endif
     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    create_simulation
      * Signature: ()J
      */
     JNIEXPORT jlong JNICALL Java_org_nwn_ts_simulation_TrainBridge_create_1simulation
     (JNIEnv *, jobject);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    delete_simulation
      * Signature: (J)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_delete_1simulation
     (JNIEnv *, jobject, jlong);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_hub
      * Signature: (JLjava/lang/String;)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1hub
     (JNIEnv *, jobject, jlong, jstring);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_station
      * Signature: (JLjava/lang/String;CIIIIID)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1station
     (JNIEnv *, jobject, jlong, jstring, jchar, jint, jint, jint, jint, jint, jdouble);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_rail
      * Signature: (JLjava/lang/String;Ljava/lang/String;III)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1rail
     (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_train
      * Signature: (JLjava/lang/String;Ljava/lang/String;C)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1train
     (JNIEnv *, jobject, jlong, jstring, jstring, jchar);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    set_train_active
      * Signature: (JLjava/lang/String;Z)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_set_1train_1active
     (JNIEnv *, jobject, jlong, jstring, jboolean);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    set_station_active
      * Signature: (JLjava/lang/String;Z)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_set_1station_1active
     (JNIEnv *, jobject, jlong, jstring, jboolean);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    set_hub_active
      * Signature: (JLjava/lang/String;Z)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_set_1hub_1active
     (JNIEnv *, jobject, jlong, jstring, jboolean);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    set_rail_active
      * Signature: (JLjava/lang/String;Ljava/lang/String;Z)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_set_1rail_1active
     (JNIEnv *, jobject, jlong, jstring, jstring, jboolean);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_maintenance_edge
      * Signature: (JILjava/lang/String;Ljava/lang/String;I)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1maintenance_1edge
     (JNIEnv *, jobject, jlong, jint, jstring, jstring, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_maintenance_train
      * Signature: (JILjava/lang/String;I)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1maintenance_1train
     (JNIEnv *, jobject, jlong, jint, jstring, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    configure_train
      * Signature: (JCIIII)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_configure_1train
     (JNIEnv *, jobject, jlong, jchar, jint, jint, jint, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    configure
      * Signature: (JIII)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_configure
     (JNIEnv *, jobject, jlong, jint, jint, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    configure_weather
      * Signature: (JIF)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_configure_1weather
     (JNIEnv *, jobject, jlong, jint, jfloat);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    repeatable_route
      * Signature: (J)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_repeatable_1route
     (JNIEnv *, jobject, jlong);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_repeatable_freight_route_stop
      * Signature: (JLjava/lang/String;Ljava/lang/String;CII)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1repeatable_1freight_1route_1stop
     (JNIEnv *, jobject, jlong, jstring, jstring, jchar, jint, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_repeatable_passenger_route_stop
      * Signature: (JLjava/lang/String;I)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1repeatable_1passenger_1route_1stop
     (JNIEnv *, jobject, jlong, jstring, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    daily_route
      * Signature: (JI)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_daily_1route
     (JNIEnv *, jobject, jlong, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_daily_freight_route_stop
      * Signature: (JLjava/lang/String;Ljava/lang/String;II)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1daily_1freight_1route_1stop
     (JNIEnv *, jobject, jlong, jstring, jstring, jint, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    add_daily_passenger_route_stop
      * Signature: (JLjava/lang/String;I)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_add_1daily_1passenger_1route_1stop
     (JNIEnv *, jobject, jlong, jstring, jint);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    reset
      * Signature: (J)V
      */
     JNIEXPORT void JNICALL Java_org_nwn_ts_simulation_TrainBridge_reset
     (JNIEnv *, jobject, jlong);

     /*
      * Class:     org_nwn_ts_simulation_TrainBridge
      * Method:    start
      * Signature: (JLjava/lang/String;)Ljava/lang/String;
      */
     JNIEXPORT jstring JNICALL Java_org_nwn_ts_simulation_TrainBridge_start
     (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
