/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_nwn_ts_util_Bridge */

#ifndef _Included_org_nwn_ts_util_Bridge
#define _Included_org_nwn_ts_util_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nwn_ts_util_Bridge
 * Method:    startSimulation
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;FIZII)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_nwn_ts_util_Bridge_startSimulation
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jfloat, jint, jboolean, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
