/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


/* Header for class org_nwn_ts_util_validator_data_TrainBridge */

#ifndef _Included_org_nwn_ts_util_validator_data_TrainBridge
#define _Included_org_nwn_ts_util_validator_data_TrainBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_nwn_ts_util_validator_data_TrainBridge
 * Method:    hub
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_nwn_ts_util_validator_data_TrainBridge_hub
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_nwn_ts_util_validator_data_TrainBridge
 * Method:    station
 * Signature: (Ljava/lang/String;CIII)V
 */
JNIEXPORT void JNICALL Java_org_nwn_ts_util_validator_data_TrainBridge_station
  (JNIEnv *, jobject, jstring, jchar, jint, jint, jint);

/*
 * Class:     org_nwn_ts_util_validator_data_TrainBridge
 * Method:    rail
 * Signature: (Ljava/lang/String;Ljava/lang/String;III)V
 */
JNIEXPORT void JNICALL Java_org_nwn_ts_util_validator_data_TrainBridge_rail
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint);

/*
 * Class:     org_nwn_ts_util_validator_data_TrainBridge
 * Method:    train
 * Signature: (Ljava/lang/String;Ljava/lang/String;C)V
 */
JNIEXPORT void JNICALL Java_org_nwn_ts_util_validator_data_TrainBridge_train
  (JNIEnv *, jobject, jstring, jstring, jchar);

/*
 * Class:     org_nwn_ts_util_validator_data_TrainBridge
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nwn_ts_util_validator_data_TrainBridge_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_nwn_ts_util_validator_data_TrainBridge
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_nwn_ts_util_validator_data_TrainBridge_start
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
